name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilar o teste
      run: gcc test_listaox.c -o test_listaox
    - name: executar o teste
      run: ./test_listaox
    - name: compilar o programa principal
      run: gcc listaox.c -o listaox
    - name: executar o programa principal
      run: ./listaox O X X X X O O X X
